### ISSUE TITLE
High FPS but looks laggy

### ISSUE THREAD

**Issue by Kyrish901** [Cazadorsniper/PO3#104]
Hi,
When i started playing the modpack, is saw that my FPS was around 80 to 90 but very thing was looking kinda laggy. it felt is was like 20 to 30 FPS while playing.

I have it on Fullscreen and i have tried vsync but did not help.

does someone have a idea how to fix that?
Thank you

**Comment by Zapstur** [comment]
Have you put a limit on your max framerate?  If so, try turning it off.  If that doesn't immediately solve the issue, run DXDiag to check the speed of your CPU; keep in mind that two CPU units with speeds that appear identical at first are actually VERY different, an Intel CPU will almost always be better at running most programs than an AMD CPU, due to AMD's focus on security and stability.

Personally, the laptop I run the Modpack on has an Intel CPU that runs at 2.5 GHz, and it runs just fine at about 110 FPS (this laptop would normally run at about 85 FPS if not for a few settings changes I have made) as long as there aren't a few hundred entities within a few chunks of my character.

**Comment by Zapstur** [comment]
I should clarify that is without Optifine, the Modpack actually runs worse with it for my system.
