### ISSUE TITLE
Game Freezes While Searching in JEI

### ISSUE THREAD

**Issue by William2467** [Cazadorsniper/PO3#107]
Pack Version:
3.0.38

Description:
When I search in JEI, quite frequently the game will freeze as I type, if I then try to close the game while it freezes, the next time I load it up it would freeze as soon as i try to bring up my inventory.
Currently I can solve the problem by removing JEI configs after i quit the game. But I don't think it's a proper long-term solution.
There're also several cases that the game freezes while loading, but this can be solved by clicking the quit button while it freezes and windows will ask if I want to quit or try to resume. If I click on the resume option then the game stops freezing and continues to load.

Steps to reproduce:
Have Java 8 update 202 64 bit
Open MultiMC
Download & Run PO3
Start a new world
Search in JEI for a few times
The game freezes while searching

Crash log:
Can't get any crash log as the game doesn't know it actually has crashed.

Additional Information:
Minecraft Launcher:
MultiMC & HMCL (can't use Twitch as my internet connection to Twitch is not practical)

PC configuration:
CPU: Intel i9-9900K
RAM: 32GB(4x8GB) DDR4 @3000MHz
GPU: NVIDIA Quadro P2000
Monitor Resolution: 3840x2160
System: Windows 10 Pro
Java Version: Java 8 update 202 64 bit
RAM allocated for Minecraft: 8GB, 12GB, 16GB (I've tried several settings)

I'm not a native English speaker so please forgive me if my expressions are unclear.

**Comment by Zapstur** [comment]
First off, this is actually normal on most systems, being that the Search function has to go through EVERY item listed (there are a LOT of them).  That being the case, let's go over how exactly JEI finds items based on various pieces of info (the name being the simplest).

1.) When Forge is setting up the game, it reads the drive where Minecraft is installed.

2.) Forge then takes each mod and its code, and creates a huge list of all the items in the game, all their recipes, and other bits of data, such as Textures and the OreDictionary.

3.) Forge then stores that data in the installation folder, to be used later by mods such as JEI.

4.) In-game, when you use JEI's search function, it must access, read, and process ALL of that data, every time something in the search is changed, such as adding or removing letters from the search box

5.) JEI then creates a secondary set of data, containing all of those search results

6.) JEI then pulls that secondary set of data when it is needed; for instance, when opening the Inventory

Taking all of that, as well as the system specifications you listed, into account, means that there are two likely causes for the game freezing.

Possible issue #1: Some of your drivers might be out of date, try getting some of them updated

Possible issue #2: The game is having a hard time accessing the drive where the game is stored, either due to being almost full, drivers being out of date, the drive being "fragmented" (various related pieces of information being spread all across the drive's sectors), or even something as simple as the drive not being fast enough.

**Comment by William2467** [comment]
> First off, this is actually normal on most systems, being that the Search function has to go through EVERY item listed (there are a LOT of them). That being the case, let's go over how exactly JEI finds items based on various pieces of info (the name being the simplest).
> 
> 1.) When Forge is setting up the game, it reads the drive where Minecraft is installed.
> 
> 2.) Forge then takes each mod and its code, and creates a huge list of all the items in the game, all their recipes, and other bits of data, such as Textures and the OreDictionary.
> 
> 3.) Forge then stores that data in the installation folder, to be used later by mods such as JEI.
> 
> 4.) In-game, when you use JEI's search function, it must access, read, and process ALL of that data, every time something in the search is changed, such as adding or removing letters from the search box
> 
> 5.) JEI then creates a secondary set of data, containing all of those search results
> 
> 6.) JEI then pulls that secondary set of data when it is needed; for instance, when opening the Inventory
> 
> Taking all of that, as well as the system specifications you listed, into account, means that there are two likely causes for the game freezing.
> 
> Possible issue #1: Some of your drivers might be out of date, try getting some of them updated
> 
> Possible issue #2: The game is having a hard time accessing the drive where the game is stored, either due to being almost full, drivers being out of date, the drive being "fragmented" (various related pieces of information being spread all across the drive's sectors), or even something as simple as the drive not being fast enough.

Thank you, Zapstur, your response is very appreciated.

However, I failed to mention that I am using a totally brand new and powerful PC, with my game installed on a super fast 500GB PCI-e SSD driver with plenty of empty space. So I don't think it is the driver that caused the issue. Also after I removed the config files for JEI and having played for a while, it seems that the problem is solved, I could search in JEI fluently without a problem. So my guess is that the problem lies in the JEI's config files. But I haven't figure out which one is the cause, or if the pack stays intact after I remove the configs.

Anyway, I'll look into that when I have time, and thank you again for your reply.
