### ISSUE TITLE
Neutral Steel of the Tenth Degree not crafting into Eleventh Degree in PRC

### ISSUE THREAD

**Issue by Wonka006** [Cazadorsniper/PO3#1099]
Playing in Kappa mode and am trying to craft the Neutral Steel of the Eleventh Degree in the mekanism PRC as per the recipe and it won't craft.  I've got kerosene, oxygen, and 3 of the tenth degree ingots in there, but it just won't go.

**Comment by Spontini** [comment]
Having the same issue.

**Comment by Ax1007** [comment]
I worked out the issue (don't worry, its still a bug).

The power consumption for the 11th metal is set far far too high. Basically you need to max out the number of energy upgrades to 8, and CANT use more than 2 speed upgrades, otherwise the power consumption is more than the machine can hold.

The seems straightforward. With 8-8 upgrades, Mekanism machines should not consume more power than that can hold.

So either the PRC needs to hold more energy(it only holds 8k maxed out vs the CIC with 640k) or the energy requirements need to be lowered.

**Comment by Wonka006** [comment]
Oh, interesting.  I'll try that next time I hop onto my world.  Thanks!

**Comment by Cazadorsniper** [comment]
Time to make it consume max long.

**Comment by Cazadorsniper** [comment]
Increased energy storage within the PRC
