### ISSUE TITLE
PNC:R Manual recipe is disabled

### ISSUE THREAD

**Issue by duguamik** [Cazadorsniper/PO3#1127]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.2.55
**Pack Mode: Kappa
**Singleplayer, Multiplayer, or LAN?: Multiplayer, Singleplayer

**Description: The PNC:R Manual manual recipe seems to be disabled. I am unable to find it in the JEI search, and am unable to create is using the normal shapeless crafting recipe (a book and compressed Iron). It's possible the recipe has been changed for Kappa mode, however without being able to search it in JEI I am unable to produce the book. This removed the ability to use the in game manual for Pneumaticcraft: Repressurized.

**Steps to reproduce: Search "PNC:R" or even "@Pneumaticcraft" in JEI. Attempt to craft the Manual using a book and a compressed iron. Neither results in a valid recipe.

**Crash log (use pastebin or issue will be closed): N/A

**Comment by Cazadorsniper** [comment]
That manual is broken is why its disabled, I literally just crashed from using it.

**Comment by desht** [comment]
Looks like this is a long-standing bug in Patchouli which doesn't just affect the PNC:R manual (as a quick search of the Patchouli issues page shows).  I don't know what triggers it - it doesn't happen in other packs - and since 1.12.2 dev for Patchouli is about done, I doubt this will ever get fixed.
