### ISSUE TITLE
Throwing Obsidian into an IE Crusher crashes server

### ISSUE THREAD

**Issue by LateNightTic** [Cazadorsniper/PO3#1136]
3.3.57
Kappa Mode
Multiplayer

Description:
Dropping Obsidian into an IE Crusher causes a gentle shutdown of the server with an associated crash log

Steps to reproduce:
Build IE Crusher
Give power (specifically in this case Spectre relay coil)
Have output chest
Drop in obsidian

Expected Result:
4 pulverised obsidian in output chest

Result:
Server crashes

Stacktrace:
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityMultiblockMetal$MultiblockProcess.doProcessTick(TileEntityMultiblockMetal.java:563)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityMultiblockMetal.func_73660_a(TileEntityMultiblockMetal.java:342)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityCrusher.func_73660_a(TileEntityCrusher.java:96)
	at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38)

[crash-2020-05-12_01.31.11-server.txt](https://github.com/Cazadorsniper/PO3/files/4612758/crash-2020-05-12_01.31.11-server.txt)

https://pastebin.com/HYg30uC2

**Comment by LateNightTic** [comment]
https://pastebin.com/HYg30uC2

**Comment by Frikkle** [comment]
I just encountered the same issue after throwing Obsidian into the Immersive Engineering Crusher.

Steps we took in finding out more about the issue:
- After crash -> restart server; the crusher kept "working" while not producing output. As if it was still processing the item.
- Then, I tried getting the item out, by jumping into the crusher, causing an immediate crash. Most likely due to my player being in there, causing a (multi-)block update.
- Restarting the server caused a crash-loop after that.
- I restored a backup, after which we had no issues anymore.
- We broke and re-built the multiblock and tried throwing in Obsidian again, causing an instant crash. The log is linked below.
- Crushing something like Coal worked as expected.

Pastebin link: https://pastebin.com/cwV0b5JA

**Comment by kil0byt3** [comment]
How was this fixed? I'm having the same issue with a different pack and this is the only trace of this crashlog I could find.

**Comment by Cazadorsniper** [comment]
Update Netherendingores

**Comment by kil0byt3** [comment]
Appreciate it. Found the fix here for any who may come after me. https://github.com/ICannt/Netherending-Ores/issues/24
