### ISSUE TITLE
Kappa Mode: Eletrotine and Red Alloy inconsistency

### ISSUE THREAD

**Issue by LogicFalls** [Cazadorsniper/PO3#1194]
**Pack Version:**
3.3.57
**Pack Mode (Normal, Titan, Kappa):**
Kappa
**Description:**
Red Alloy can either be made with 8 redstone and an iron ingot, compounded and smelted, or an alloy of 4 redstone and a copper ingot. The latter recipe can _only_ be performed in the immersive Engineering Arc Furnace or Immersive Engineering Alloy Kiln, which is highly irregular for alloys. Obviously, this recipe is desirable for efficiency reasons, and is used exclusively.

Electrotine alloy can be made in the same manner as the Red Alloy, excluding the Arc Furnace recipe. As alloy kilns are multiblocks that cannot be interacted with mechanically, this means it is impossible to automate the efficient production of Eletrotine alloy. The kilns are cheap, earlygame structures that use burnable fuel. As they are the only device to feature these efficient alloy recipes, they feel like an oversight.

The proposed solution is to either remove the Arc Furnace and Alloy Kiln recipes for the alloys and have the only means of creating them be using 8 of their dusts and smelting the compound, or, alternatively, expand the efficient production of the alloys using 4 dust and a copper ingot to any alloying machine (EIO Alloy Smelter, TE Induction smelter, NC Alloy Furnace).

**Comment by Frikkle** [comment]
Heya, I just ran into this in Kappa mode as well; but in contrast to the issue creator I don't mind Red Alloy Ingot being available only in the Arc Furnace and the Immersive Engineering Alloy Kiln; since the Arc Furnace can be automated.

However, I do think that it is strange that Electrotine Alloy Ingot cannot be made in the Arc Furnace.

@Cazadorsniper you labeled this as a "won't fix"; does this also include "adding an Arc Furnace recipe for Electrotine Alloy Ingot"? Or is it intended?
