### ISSUE TITLE
Crash on fighting (Ticking entities)

### ISSUE THREAD

**Issue by litch76** [Cazadorsniper/PO3#121]
It happens when i'm fighting some mobs. It happened multiples times, in overworld and in the twilight forest. I changed my weapon and nothing changed

https://pastebin.com/1fp8RdUw
https://pastebin.com/ck8vnc3j

**Comment by Cazadorsniper** [comment]
Have you tried updating the pack?

**Comment by Hextaine** [comment]
I had a similar issue. Do you have any Nian Zhus / mob charms from Reliquary currently equipped? My issues arose specifically from trying to damage a zombie while wearing a Zombie Charm. I used an alternate account to log onto the server and killed the zombie before logging back onto the account that had the Nian Zhus equipped.

**Comment by AnorakThePrimordial** [comment]
I do not have any nian zhus equipped and i am having the same issue. It didnt generate a crash report for some reason though. This is a big problem because i am currently in the nether and surrounded by mobs. My main weapon is The Ender that i got as loot and it has empowered 3 i think? not sure if that is related but just tossing out info since i cant provide a crash log

**Comment by AnorakThePrimordial** [comment]
oh also, i think i am on the latest version? 3.0.39
