### ISSUE TITLE
PO3 Crashes when started with MultiMC

### ISSUE THREAD

**Issue by WClampitt1** [Cazadorsniper/PO3#1220]
I tried importing the zip file into MultiMC and when I tried to launch PO3, it crashed every time I tried it. I will leave the Minecraft log below. I am not sure what is going on here. I am running it on a machine running Fedora 31, but I don't have a ton of experience troubleshooting Minecraft Mods, so I would really appreciate some help with this.

https://paste.ee/p/DHNU8

**Comment by Cazadorsniper** [comment]
Can't start it with the twitchapp?

**Comment by DeusFacticius** [comment]
> Can't start it with the twitchapp?
Twichapp is crap on non-windows platforms.

> I tried importing the zip file into MultiMC and when I tried to launch PO3, it crashed every time I tried it. I will leave the Minecraft log below. I am not sure what is going on here. I am running it on a machine running Fedora 31, but I don't have a ton of experience troubleshooting Minecraft Mods, so I would really appreciate some help with this.
> 
> https://paste.ee/p/DHNU8

I ran into this issue on OSX, but the problem is the same for any platform: you're version of Java is too new.  

Although minecraft isn't too picky about the Java version, Forge uses some bytecode manipulation / injection techniques that simply don't work on newer versions.  To run PO3 (or really any mc 1.12 + forge modpacks) you'll need to install Java 8 (aka 1.8).  

I don't have my Fedora machine handy to search the package repos for the exact package name, but I believe it's 'java-1.8.0-openjdk' that you want.  You may have to configure / enable third party repos to find the appropriate package, java-1.8 is pretty old now.
