### ISSUE TITLE
Certus Quartz Seeds cannot be inserted into the Phytogenic Insolator like the recipe states

### ISSUE THREAD

**Issue by Cellidor** [Cazadorsniper/PO3#1221]
**Pack Version:** 3.3.58A
**Pack Mode (Normal, Titan, Kappa):** Normal
**Singleplayer, Multiplayer, or LAN?:** Singleplayer/LAN

**Description:** Certus Quartz Seeds have a recipe stating they can be inserted into the Phytogenic Insolator with glowstone to make pure certus quartz crystal. The Phytogenic Insolator will accept glowstone into the appropriate slot, but not the certus quartz seed. The recipe may also not function with the Enrichment Chambers, I don't have the plastic to build them and test.

**Steps to reproduce:**
1. Craft a Certus Quartz Seed with sand and certus quartz dust
2. Place a Phytogenic Insolator and ensure it has power/water
3. Unlock the fertilizer slot and attempt to insert the Certus Quartz seed and glowstone dust

Result: Can insert glowstone dust but cannot insert seed into the machine.
![phyto](https://user-images.githubusercontent.com/5710572/83290263-5fb36900-a1b4-11ea-8205-6e9d1e849136.png)

**Comment by VoidedOut** [comment]
My suggestion would be to use the crystal growth chamber or enrichment chamber, since they’re better anyways. This isn’t a fix to the problem though

**Comment by i00** [comment]
> My suggestion would be to use the crystal growth chamber or enrichment chamber, since they’re better anyways. This isn’t a fix to the problem though

They are certainly not better:

- harder to automate (if this bug was fixed that is :P)
- take up more space
- slower (the phytogenic insulator takes < 4 seconds on the base level)

It does work eventually ... if you try several times - you will need to keep closing the interface and reopening it again.
I have it hooked up to a fluid transposer that drains water from a emperor's chalice for infinite water... but, due to another bug with the insulator, you will need to pump the water to it with a pipe (I use Ender IO's fluid conduits) rather than from the transposer directly.

**EDIT**:
The most consistent way I find I can get it to work is to drag and drop the seeds in, then close the interface (they will pop out when this happens), then useualy when you go back into the interface and shift + click on them (do not drag) the will then start processing!
