### ISSUE TITLE
mobs killing me in one hit

### ISSUE THREAD

**Issue by Jaders2** [Cazadorsniper/PO3#1301]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
**Pack Mode (Normal):**
**Singleplayer**

**Description:**

the vast majority of mobs are giving me hit kill, even with absorption, regeneration and heart canister, and I don’t know if it’s normal or bug.

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by CactusCool** [comment]
Hi this issue is most likley caused by difficulty scaling, when you kill a boss like a wither the game gets harder and the mobs do more damage. If your using with Draconic Evolution mob grinder it counts it as player kills and after a certain amount of them are killed mobs will one shot you unless you are in the armors that make you invincible the armor from overloaded and the one from avaritia.

**Comment by Jaders2** [comment]
and have a way to reset the counter?

**Comment by VoidedOut** [comment]
I’ve actually had a spider in the deep dark that no matter what I couldn’t kill, and it one shot me through draconic armor. It was a big rip

**Comment by CactusCool** [comment]
To my knowledge, the only way to counter this is to use the multi armor or the infinity armor. You might be able to reset the file if you look into the code but I'm not sure, the multi armor is quite cheap so I suggest you make that depending on the pack mode. Even in kappa it's not to bad though

**Comment by Cazadorsniper** [comment]
Delete ESM.dat or epicsiegemod.dat in world folder.
