### ISSUE TITLE
cant install pack due to missing addon

### ISSUE THREAD

**Issue by BattlFire** [Cazadorsniper/PO3#1345]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.5.59**
**Pack Mode: Normal**
**None**

**Description:**
![Skjermbilde](https://user-images.githubusercontent.com/69515426/89897771-d8389c00-dbdf-11ea-97b1-2be65479903e.PNG)

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by meerpaluten** [comment]
I have the same error/problem

**Comment by meerpaluten** [comment]
This is an issue with the twitch app, just restart and try again, make sure you have a stable internet connection

**Comment by Leigham** [comment]
This seems to be a major issue with twitch, tried relaunching, reinstalling, changing what drive, and i have 150/20 speeds, no idea what the issue is, its doing it with all modpacks, kinda stuck rn

**Comment by neyhr** [comment]
got the same issue...

**Comment by alucardbrn** [comment]
Same here, but after trying to reboot app and computer (just reinstalled SO on my machine because of a hardware upgrade), I got almost the same msg. If this one has more info to help fix it...

Cannot find file System.Linq.Enumerable+WhereSelectListIterator`2[Curse.Radium.Minecraft.Models.ManifestResource,System.Int32] for addon 226406 in database. Aborting installation.

**Comment by andreivoinea** [comment]
Not dev or anything but been scouring the internet today for an answer to this. It's most likely a twitch thing. It happened to almost all mods. Most likely we'll have to wait for Twitch to fix it...
