### ISSUE TITLE
It crash when I try to move

### ISSUE THREAD

**Issue by humanarw** [Cazadorsniper/PO3#1602]
**Pack Version:**
po3-3.4.4
**Pack Mode (Normal, Titan, Kappa):**
normal
**Singleplayer, Multiplayer, or LAN?:**
singleplayer
**Description:**
I get into the world and when I press any key,it crash
**Steps to reproduce:**
get in and crash
**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/cEGbjxb7

**Comment by Cazadorsniper** [comment]
Try reinstalling the pack.

**Comment by humanarw** [comment]
https://pastebin.com/8w7ZTCEc
https://pastebin.com/NjB6sZ4q
https://pastebin.com/2r4TJukb
https://pastebin.com/KjkDxNjd
https://pastebin.com/eKaU2CWT
I reinstalled but It got worse

**Comment by cnordbakk** [comment]
How much RAM do you have allocated? This seems to be a memory issue with JEI.

**Comment by humanarw** [comment]
I gave it 8Gb

**Comment by Cazadorsniper** [comment]
Did you add any mods?
Are you able to install the modpack in a different location on the HDD/SSD?
I read some where that sometimes old versions of Minecraft crashes due to updated versions of minecraft having more keybinds, so you could try deleting the options.txt file to see if that works.
If none of that is causing the issue then I don't know what could be the issue without the crash report (those are logs not crash reports).

**Comment by humanarw** [comment]
Well... I'm sure that I didn't add any mods
I will try those ways later
And...I sorry that I put the log because this is my first time trying to fix minecraft problem,so I don't know the log is not crash report

**Comment by humanarw** [comment]
my minecraft doesn't give me crash reports

**Comment by Cazadorsniper** [comment]
I don't know what the cause could be then. Maybe another program is causing the crash, I don't know.
