### ISSUE TITLE
Steelleaf armor found in twilight can be used to skip a majority of armorplus

### ISSUE THREAD

**Issue by InfornoFire** [Cazadorsniper/PO3#166]
**Pack Version:**
3.0.38
**Description:**
You can get steelleaf armor in twilight and then use it to craft knightmetal armor and skip a bunch of armor sets.
**Steps to reproduce:**
Just find steelleaf armor in a chest from a place like the Dark Forest Ruins in Twilight and you can use it to craft other armor pieces

**Comment by PrimeroBestia** [comment]
It's the same with the armor mobs drop(steel, lapis, glowstone) and later armors do this too, the problem with going that route is that, you won't unlock the other quest if you skip the armors in between, so doing is kind of pointless unless you don't really care about quests. I don't think this is an issue, especially if you want to keep earlier armors, e.i. the yeti armor, it's less of an hassle this way, because you don't have to keep crafting the previous armors.
