### ISSUE TITLE
Chicken Chunks chunk loader doesnt work across dimensions (Not sure if bug or feature?)

### ISSUE THREAD

**Issue by KlayTitan** [Cazadorsniper/PO3#185]
**Pack Version:**
3.0.38

**Description:**
So I have a Ender Chest (Ender Storage one) hooked up to my AE2 computer which dumps whatever is in it to the computer fine when I'm in the overworld, but if I am in any other dimension besides the overworld it doesn't move any of the chest inventory into the computer, I saw that forge chunk keeping was disable, and to use the chicken chunks chunk loader, which I am, but it doesn't seem to work as soon as I teleport to any other dimension, I've tried the Nether, the End, Erebus, Hunting, Abyssal Craft dimensions, the Void, etc and they all seem to keep the the items from going into the computer, So I thought, maybe it's something on AE2's end, but I made a wireless crafting terminal with an infinity booster card in it, and when I travel to another dimension I Can use it for about 5 seconds before it says "no network power". Now I'm pretty sure my multiple power generators are inside the Chunk loaders radius. So the only thing I can figure is that the chunk loader is not working when I am not in the same dimension as it. If this is an intended feature that's fine, but no amount of googling and checking the reddit has given any answers. I am in a Garden of Glass world if that matters.

**Steps to reproduce:**
Build a AE2 compute system
See if you can access it outside of the overworld with a Chicken Chunks Loader keeping the computer and Power for it loaded using wireless or ender chest/pouch from Ender Storage.

**Crash log <use pastebin or similar>:**
No crash to report

**Comment by martinschuberteu** [comment]
Do you maybe have claimed chunks also chunk loaded with FTB Utilities (red on the map)? I had the same issue but using only a chicken chunk loader works for me.

**Comment by KlayTitan** [comment]
I doesn't look like I do, but I hit unclaimed all just to be safe, I moved a chunk loader closer to my power and increased it's range. and it seems to be working at the moment, but I'm not sure how moving the chunk loader to just one chunk over made it work, when I had the thing already on radius 2 which, given the lasers, was already covering the power gen. Unless I'm completely wrong on what a chunks size actually is...

**Comment by martinschuberteu** [comment]
Claiming chunks should be ok and if it's within the laser beams it should be loaded.

**Comment by bigmaciraq** [comment]
I've had chicken chunks loader successfully keep chunks loaded in Twilight Forest (Pumping oil while overworld) before, so it is something more specific here.

**Comment by deadspidervenom** [comment]
FTB utilities chunk loading is really bad i would suggest never using if given the option not to. I found this out when i was playing "Age of Engineering".

To give a short description of why from my USE of the two mods (not from reading the code). FTB Utilities seems to do a soft load of the chunks, so machines and the such will run, but does not actually keep the chunks loaded, i found this out because i made a cow pit in AoE and my cows would randomly burst of it when i went to like the nether and came back. forcing me to kill them and wait for them to breed back up.

Where as almost any other chunk loader will actually load the chunks.

So my suggestion is this. If you plan to be in the area of the chunks a lot use FTB utilities. If its outside the chunk loading radius of the player, use something else.

**Comment by Cazadorsniper** [comment]
This might happen because Wireless crafting terminal has a config to have the ME Controller chunkload itself which may conflict with other chunkloaders, already fixed next update.
