### ISSUE TITLE
Crafting items in the ME crafting terminal with encoded patterns causes tps to lower exponentially

### ISSUE THREAD

**Issue by theantiangaming233** [Cazadorsniper/PO3#238]
**Pack Version3.0.39:**
**Single-player**

**Description:When auto-crafting in ME crafting terminal, tps breaks for a small while**

**Steps to reproduce:Crafting from a encoded pattern causes the tps to lower exponentially. Example:Draconic Energy Core**

**Crash log (use pastebin or similar):
![2019-03-30_19 37 54](https://user-images.githubusercontent.com/25700232/55283211-70075400-5323-11e9-8622-43e55fd9a387.png)
**

**Comment by banggugyangu** [comment]
While this may not be the case in this situation, This very often times happens when an AE network is poorly designed.  It's very easy to make an inefficient network that drags the server performance down.  (Yes, being single player still has a server side.)  It may indeed be a problem with either the mod or the pack, but I would suggest ensuring that your AE network uses best practices in all aspects, also.
