### ISSUE TITLE
Metallurgic quest under Tau not completing

### ISSUE THREAD

**Issue by vilequarter** [Cazadorsniper/PO3#242]
**Pack Version:** 3.0.39
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** When holding a Matallurgic Infuser from Mekanism in the player's inventory, the quest book will not detect it as a completion for the quest. Tried with upgrades in the infuser, no upgrades, energy in the infuser, no energy, and newly crafted.

**Steps to reproduce:** Have the Metallurgic quest unlocked under Tau, craft a Metallurgic Infuser, attempt to complete the quest.

**Crash log (use pastebin or similar):** N/A

**Comment by Cazadorsniper** [comment]
probably because nbt data, maybe.

**Comment by saulysw** [comment]
I have the same issue. There is a pre-requirment for "explosive crafting" or something similar, and I've completed that. It no longer shows any pre requirements, but having a Metallurgic Infuser in inventory does not trigger the quest. Making a new one doesn't either. This is bad because it is the start of doing the whole mod in the questbook.
