### ISSUE TITLE
Problem with the void

### ISSUE THREAD

**Issue by kyletherenegade** [Cazadorsniper/PO3#332]
**Pack Version:**3.0.40
**Singleplayer, Multiplayer, or LAN?:**
multiplayer
**Description:*void is kick my friend out for falling into the void and the game doesn't know where to place my friend that what i think about the crash we having

**Steps to reproduce:**friend fell in the void then the server kick him then he trying to join back then the server crash

**Crash log (use pastebin or similar):**
[crash-2019-04-26_00.16.27-server.txt](https://github.com/Cazadorsniper/PO3/files/3119696/crash-2019-04-26_00.16.27-server.txt)

**Comment by Cazadorsniper** [comment]
Seems to have something to do with Extra Utilities 2.

**Comment by kyletherenegade** [comment]
then ill send this crash log to extra utilities 2 i guess

**Comment by Cazadorsniper** [comment]
It may not be Extra Utils though...

**Comment by kyletherenegade** [comment]
so here what happening i fell in the spot my friend fell last night and when i go the nether by the void its teleport more to like 50 different places in a single second which kick me friend out of the server and may cause the crash

**Comment by Cazadorsniper** [comment]
I'll make my own server and test this out, just need to wait.

**Comment by kyletherenegade** [comment]
here ill be more useful if u watch this https://www.twitch.tv/videos/416969261
then me typing it with my broke english

**Comment by PhunStyle** [comment]
This has been happening on our server as well. One player falls into the void, they go on this wild teleport loop until the server kicks them out or they lose connection - it also sometimes crashes the entire server.

Sadly i don't have a crash log at the moment. I already removed journeymap from the server mods and ingameinfoxml from the server mods as suggested on a few other places, but this didn't actually fix the problem.

It visually looks the same as in the twitch clip above where the items keep appearing and disappearing in the hotbar. But my friends can't reconnect afterwards, it just errors out and they get kicked unless i manage to go to the nether myself, tp them to me in the split second they're online, after which they still disconnect but then finally after reconnecting a second or sometimes third time they're able to move again. 

It's really been annoying because this has made us have to restart the server quite a couple of times which takes like ten minutes so it kinda makes us lose the excitement to play the pack!

Hoping for some updates soon! If i can get a crash report from whenever my friend decides to come online again, i'll definitely add it later on!

**Comment by Cazadorsniper** [comment]
Reported to mod dev.

**Comment by nzminecraftDOTcom** [comment]
Reports of it happening on my server too.
Jumped on to try it out and this (see paste) repeats over and over until a disconnection occurs with "Timed Out" as the reason. 
https://pastebin.com/4XbM0z8Y
Falling into the nether worked once, but doing it elsewhere seems to cause this bug.

**Comment by kevinvanbr** [comment]
so still no solution?

**Comment by Cazadorsniper** [comment]
No.

**Comment by CasualCucumber** [comment]
Has there been a solution to this problem yet?

**Comment by Cazadorsniper** [comment]
no
