### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by MariusROBERT** [Cazadorsniper/PO3#60]
Hi everybody,
I downloaded this pack because I love modded minecraft but when I launched it, the game crashed, I tried many times, download the mudpack again but nothing changed : the windows appear and disappear like 1 second after.

Here's my [crash report](https://pastebin.com/8VgEiVuZ)

**Comment by Zapstur** [comment]
Well, first off, you haven't allocated enough RAM to the game.  This modpack needs AT LEAST 6 GB of RAM, 7 or more on some systems.  Try fixing that via the Minecraft Launcher, then see if that solves the problem.  

If, however, you can't allocate that much RAM due to hardware limitations, then you are out of luck, and won't be able to play.  Yes, there are methods to artificially boost available RAM, however most of them require things to be unloaded from the physical RAM on the system, and THAT will cause far more problems than playing any modpack is worth.

**Comment by MariusROBERT** [comment]
Ok, I currently have 8 GB so I gonna try with 6GB allocated and it's true that my computer is pretty old (early 2009 ^^')

**Comment by Zapstur** [comment]
8 isn't going to work for you, since your computer's OS needs some too.  Go with 7 GB.

**Comment by MariusROBERT** [comment]
I tried with 7GB max and 8GB max but that don't work on both, I think my computer is really too old and my RAM isn't the only problem, it was really cool to play on PO2 but I gonna need a better computer to play on PO3

Thanks for trying to help me
