### ISSUE TITLE
No Rain Particles

### ISSUE THREAD

**Issue by minimuscle** [Cazadorsniper/PO3#61]
So I have no rain particles. It rains, (barrels don't fill up but that might be a modpack thing, the sky goes grey), I hear no noise and I'm in a plains biome. Tries this on the Garden of Glass and superflat worlds.

I use SEUS Shaders and really want to see the rain, however, I have taken both the shaders and optifine out and still nothing. All particles are enabled and im not sure what else to do.

**Comment by Zapstur** [comment]
Since you have Optifine, you need to check various other sections of the settings.  If every setting you can find says that rain/snow is supposed to be visible, then there is probably something wrong with that shader.  This is not a problem with the modpack itself, and probably should have been asked about elsewhere, since this section of GitHub is exclusively for things to do with the PO3 modpack.

**Comment by DangerHSW** [comment]
PO3 has rain particles and sound disabled by default with a mod called "no more rain"

**Comment by Cazadorsniper** [comment]
if want to see rain remove the biometweaker scripts called rainless

**Comment by NightRadz** [comment]
checked for 'rainless' in scripts and anything related to biometweak and nothing exists. there isnt even any scripts. if you could explain where to find what disables rain because barrels aren't filling because rain is non existent.

**Comment by DangerHSW** [comment]
![Capture](https://user-images.githubusercontent.com/48067686/54788296-ce02b000-4c2e-11e9-9fbc-4454fd0b8c5d.PNG)
![Capture2](https://user-images.githubusercontent.com/48067686/54788297-ce02b000-4c2e-11e9-946a-e0b388757740.PNG)
