### ISSUE TITLE
Needed In-Game Account Switcher

### ISSUE THREAD

**Issue by Cazitron** [Cazadorsniper/PO3#72]
There is too many times where when we try to login to a server we get failed to login. (Invalid session) if you could just incorporate a mod along these lines so we don't have to wait 5 minutes every time to load the launcher, if it is even five minutes.

**Comment by Zapstur** [comment]
A mod like that isn't even possible, since the log-in MUST be done through the Minecraft Launcher, and not in-game.  The reason it has to be done like that, is because each login has to be checked by Microsoft before the game will even boot up.  Having something like that in-game would create risks to account security, and that alone would be enough for a mod to get a C&D order.

TL;DR:  Just wait 5 minutes between login sessions.

**Comment by CraftalotReloaded** [comment]
https://minecraft.curseforge.com/projects/reauth

**Comment by Cazitron** [comment]
thank you CraftalotReloaded
