### ISSUE TITLE
Abyssalcraft Issues with rituals and Shoggoth

### ISSUE THREAD

**Issue by Rithenar** [Cazadorsniper/PO3#779]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.1.45
**Pack Mode:** Titan
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**
First issue - When kiting Shoggoths to get statues (Abyssalcraft) the monoliths and statues will not generate unless I go to creative. Once they generate I go back to Survival and harvest them as usual.

Second issue - When trying to activate a ritual by shift+right-clicking with Necronomicon on Ritual Altar nothing happens. I have to restart the world in order for the ritual to happen

**Steps to reproduce:**

Issue 1 - Placed down the Shoggoth biomass and waited for Shoggoth to spawn. There were between 6-8 of them at all times and they chased me around the 30X30 obsidian cage I created. Since they were not building any monoliths I changed /gamemode to creative and 3 monoliths along with statues generated. I tried the same process 4 different time with the same results.

Issue 2 - After placing down the required materials and shift+right click with Necronomicon the altar forms with no problems. When performing a ritual I place all the components on the Pedestals as shown on JEI and shift+right-click the altar with the necronomicon. I have more than required PE and the rituals do not require a sacrifice but nothing happens, even after repeating the process several times. I exit the World and then log back in without changing anything on the pedestals or altar and then shift+right-click with Necronomicon and the ritual starts as expected

**Crash log (use pastebin or issue will be closed):** No crash with this issue.

**Comment by Cazadorsniper** [comment]
Second issue is probably fixed in an update.

First issue I couldn't replicate.

**Comment by pie3636** [comment]
Having exactly the same first issue (kappa mode, single player, 3.3.59). I have a 11x11 obsidian cage, a 5x5 square of biomass, the shoggoths are spawning, following me but not building any statue (I waited up to 20 minutes, there were usually 6-8 of them at once). After seeing this issue, I switched to creative and a statue immediately appeared. I went back to survival to mine it.
I had to repeat this process several times until I got enough statues.

Everytime I switched to creative with 6-8 mobs attacking me, the monolith appeared immediately. They never spawned otherwise.
