### ISSUE TITLE
"Cannot update, files are already in use."

### ISSUE THREAD

**Issue by swardhagen** [Cazadorsniper/PO3#803]
Hey!
I get this message when I try to update from 3.1.45 to 3.2.51 in the Twitch launcher:
"Cannot update, files are already in use. Please exit any applications that may be using the files in this profile folder."
I have tried restarting Twitch and the computer but to no avail. I have seen other modpacks having this problem but the fix is always PC-related and since I am on mac that fix doesn't work for me (changing folders to read-only). Anyone got a solution? It would be awesome to get the update since it fixed the diamond essence.

**Comment by Cazadorsniper** [comment]
Have to change it from read-only, I'm unsure why Twitchapp does that.

**Comment by Nagapito** [comment]
This always happens to me because Twitch client freaks out with the resource pack zip files, specially if they were not added by the client. Actually, he kinda freaks out with any zip file...

I always have to move to a different folder my resource packs and, if I have them, the shaders files to I can update a pack....
