### ISSUE TITLE
Unable to restore any backed up save files

### ISSUE THREAD

**Issue by RNADNA47** [Cazadorsniper/PO3#84]
**Pack Version:**
PO3.3.0.38

**Description:**

Unable to restore any of 5 save files. After the wireless crafting terminal bauble crash, where I would have to rollback as I do not know of a way to remove the wirelessc crafting terminal from the bauble slot outside of minecraft, this is a disaster. 

**Steps to reproduce:**

Play for a while. Create a lot of things. Go back and try to recover a save. 

**Crash log:**

https://pastebin.com/4RnGFgEn

**Comment by Zapstur** [comment]
Well, my suggestion would be to use an NBT editor to change the Bauble Slot to being empty, but I can't seem to find those crucial slots in my files, so that idea might be out the window.  Even looking online, it looks like nobody has found a way to edit what is in Bauble Slots.  That said, I DID find one method that might salvage your world (unfortunately all the items your character had will be gone)...  Of course, make a backup of your world folder before you try this.

------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------

1.) Find the folder for your installation of the modpack, the default location is:
C:\Documents\Minecraft\Instances\Project Ozone 3 A New Way Forward\

2.) Open the "saves" folder, then the folder with the name of your world

3.) Use an NBT Editor, such as NBTExplorer, to open the file called "level.dat" inside of that folder

4.) While using the NBT Editor, expand the entry called Data

5.) Select the entry called Player, and delete it (by pressing the red "X" in one of the top tool bars)

6.) Close the NBT Editor, and then try to load up your world again.

------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------

If this works, GREAT.  If it doesn't, then I don't think there's anything you can do other than create a new world, and use a little but of cheating to replicate the progress you had made.

**Comment by LordVulc4n** [comment]
The bauble data can be found in your playerdata file,
D:\Curse\Minecraft\Instances\Project Ozone 3 A New Way Forward\saves\New World\playerdata\(your UUID).dat

![image](https://user-images.githubusercontent.com/13063413/53797316-d8823180-3f2d-11e9-926b-48e8a61f0b97.png)
