### ISSUE TITLE
Lite version?

### ISSUE THREAD

**Issue by blahrk** [Cazadorsniper/PO3#89]
**Pack Version:**

**Description:**
Is there coming a lite version of project Ozone? My pc can't handle the pack, it just freezez when it's almost finished loading

**Steps to reproduce:**

**Crash log:**

**Comment by Zapstur** [comment]
Sounds to me like you haven't dedicated enough RAM to Minecraft.  This modpack needs AT LEAST 6 GB on most systems, 7 or more on others.  Even modpacks which only have about 30 or 40 mods still need at least 5 GB to run properly, because Minecraft itself isn't very efficient, and just gets worse the longer the Vanilla game goes without major performance improvements.  Plus there's the CPU usage on Minecraft 1.12.2, which is actually a bit weird; sometimes it uses less, sometimes it uses more, even though nothing is happening in the world.

Also, even though there are ways to artificially increase the amount of RAM in any Windows based system, ALL of those methods just create more problems for that to be worth it.

**Comment by Cazadorsniper** [comment]
There is already Project Ozone Lite for 1.10.2
