### ISSUE TITLE
AE2 autocraft calculation takes over 20 seconds

### ISSUE THREAD

**Issue by Alexaario** [Cazadorsniper/PO3#964]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:Latest
**Pack Mode:Normal
**Singleplayer

**Description:**
So when you want to autocraft something the "how many" gui comes up. After I set a wanted amount and click next it takes about 20 seconds or more for the autocraft start gui to come up. I watch one youtuber's let's play and there is no such issue in his playthrough so idk. No idea what's going on.
**Steps to reproduce:**
above idk
**Crash log (use pastebin or issue will be closed):**
no crash log. it doesn't crash.

**Comment by TrevorRuppert** [comment]
have you tried crafting something that is not step-intensive (like turning logs into planks)? also, what crafting processors are you using? 1k? 4k? 16k? 64k? etc if the recipe is step-intensive I have known it to take quite a while for it to process the recipes and it's just due to the nature of what the mod is actually doing (it's literally going through every step and all the steps leading to that step if there are pre-requisites that you have on auto-craft) I had an autocraft for 100k tesseracts on po2 and I had to leave the auto crafting GUI opened for an hour before it finally processed everything and even let me hit "start".

**Comment by GodlyIdea** [comment]
AE2 is known to have some issues with recursive recipes and with some storage systems like in issue #907 where YABBA barrel storage system caused AE crafting slowdown.

Disconnect stuff from your ME network and test when the crafting goes to normal.

**Comment by Alexaario** [comment]
Issue #907 was totally the case
